[providers]
providers = ["node"]

[variables]
NODE_ENV = "production"
PNPM_VERSION = "9.12.0"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"